<?php

namespace DoctrineProxies\__CG__\app\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \app\Doctrine\ORM\Entity\Order implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'creationDate' => [parent::class, 'creationDate', null, 16],
        "\0".parent::class."\0".'estimatedInstallDate' => [parent::class, 'estimatedInstallDate', null, 16],
        "\0".parent::class."\0".'fabricationStartDate' => [parent::class, 'fabricationStartDate', null, 16],
        "\0".parent::class."\0".'invoiceNumber' => [parent::class, 'invoiceNumber', null, 16],
        "\0".parent::class."\0".'measuredBy' => [parent::class, 'measuredBy', null, 16],
        "\0".parent::class."\0".'orderCompletedDate' => [parent::class, 'orderCompletedDate', null, 16],
        "\0".parent::class."\0".'orderId' => [parent::class, 'orderId', null, 16],
        "\0".parent::class."\0".'payments' => [parent::class, 'payments', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'product' => [parent::class, 'product', null, 16],
        "\0".parent::class."\0".'referenceNumber' => [parent::class, 'referenceNumber', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'creationDate' => [parent::class, 'creationDate', null, 16],
        'estimatedInstallDate' => [parent::class, 'estimatedInstallDate', null, 16],
        'fabricationStartDate' => [parent::class, 'fabricationStartDate', null, 16],
        'invoiceNumber' => [parent::class, 'invoiceNumber', null, 16],
        'measuredBy' => [parent::class, 'measuredBy', null, 16],
        'orderCompletedDate' => [parent::class, 'orderCompletedDate', null, 16],
        'orderId' => [parent::class, 'orderId', null, 16],
        'payments' => [parent::class, 'payments', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'product' => [parent::class, 'product', null, 16],
        'referenceNumber' => [parent::class, 'referenceNumber', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
