<?php

namespace DoctrineProxies\__CG__\app\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \app\Doctrine\ORM\Entity\Address implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'addressId' => [parent::class, 'addressId', null, 16],
        "\0".parent::class."\0".'appartmentNumber' => [parent::class, 'appartmentNumber', null, 16],
        "\0".parent::class."\0".'area' => [parent::class, 'area', null, 16],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null, 16],
        "\0".parent::class."\0".'streetName' => [parent::class, 'streetName', null, 16],
        'addressId' => [parent::class, 'addressId', null, 16],
        'appartmentNumber' => [parent::class, 'appartmentNumber', null, 16],
        'area' => [parent::class, 'area', null, 16],
        'postalCode' => [parent::class, 'postalCode', null, 16],
        'streetName' => [parent::class, 'streetName', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
