<?php

namespace DoctrineProxies\__CG__\app\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \app\Doctrine\ORM\Entity\Client implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'address' => [parent::class, 'address', null, 8],
        "\0".'*'."\0".'firstName' => [parent::class, 'firstName', null, 8],
        "\0".'*'."\0".'lastName' => [parent::class, 'lastName', null, 8],
        "\0".'*'."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 8],
        "\0".parent::class."\0".'clientId' => [parent::class, 'clientId', null, 16],
        "\0".parent::class."\0".'clientReference' => [parent::class, 'clientReference', null, 16],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null, 16],
        'address' => [parent::class, 'address', null, 8],
        'clientId' => [parent::class, 'clientId', null, 16],
        'clientReference' => [parent::class, 'clientReference', null, 16],
        'firstName' => [parent::class, 'firstName', null, 8],
        'lastName' => [parent::class, 'lastName', null, 8],
        'orders' => [parent::class, 'orders', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
